model.diffusion_model.time_embed: 0
model.diffusion_model.input_blocks: 0
model.diffusion_model.middle_block: 0
model.diffusion_model.output_blocks.0: 0
model.diffusion_model.output_blocks.1: 0
model.diffusion_model.output_blocks.2.0: cpu
model.diffusion_model.output_blocks.2.1.conv: cpu
model.diffusion_model.output_blocks.3: cpu
model.diffusion_model.output_blocks.4: cpu
model.diffusion_model.output_blocks.5: cpu
model.diffusion_model.output_blocks.6: cpu
model.diffusion_model.output_blocks.7: cpu
model.diffusion_model.output_blocks.8: cpu
model.diffusion_model.output_blocks.9: cpu
model.diffusion_model.output_blocks.10: cpu
model.diffusion_model.output_blocks.11: cpu
model.diffusion_model.out: cpu
first_stage_model: 0
second_stage_model: cpu
cond_stage_model: 0
model_ema: 0
betas: 0
_buffers: 0
alphas_cumprod: 0
alphas_cumprod_prev: 0
sqrt_alphas_cumprod: 0
sqrt_one_minus_alphas_cumprod: 0
log_one_minus_alphas_cumprod: 0
sqrt_recip_alphas_cumprod: 0
sqrt_recipm1_alphas_cumprod: 0
posterior_variance: 0
posterior_log_variance_clipped: 0
posterior_mean_coef1: 0
posterior_mean_coef2: 0
cc_projection: 0
