model:
  base_learning_rate: 0.0001
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image_target
    cond_stage_key: image_cond
    image_size: 32
    channels: 4
    cond_stage_trainable: false
    conditioning_key: hybrid
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    scheduler_config:
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps:
        - 100
        cycle_lengths:
        - 10000000000000
        f_start:
        - 1.0e-06
        f_max:
        - 1.0
        f_min:
        - 1.0
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 8
        out_channels: 4
        model_channels: 320
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        num_heads: 8
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: true
        legacy: false
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: __main__.LazyFrozenCLIPImageEmbedder
      params:
        from_pretrained: false
        clip_constructor_args:
          embed_dim: 768
          image_resolution: 224
          vision_layers: 24
          vision_width: 1024
          vision_patch_size: 14
          context_length: 77
          vocab_size: 49408
          transformer_width: 768
          transformer_heads: 12
          transformer_layers: 12
data:
  target: ldm.data.simple.ObjaverseDataModuleFromConfig
  params:
    root_dir: views_whole_sphere
    batch_size: 192
    num_workers: 16
    total_view: 4
    train:
      validation: false
      image_transforms:
        size: 256
    validation:
      validation: true
      image_transforms:
        size: 256
lightning:
  find_unused_parameters: false
  metrics_over_trainsteps_checkpoint: true
  modelcheckpoint:
    params:
      every_n_train_steps: 5000
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 500
        max_images: 32
        increase_log_steps: false
        log_first_step: true
        log_images_kwargs:
          use_ema_scope: false
          inpaint: false
          plot_progressive_rows: false
          plot_diffusion_rows: false
          'N': 32
          unconditional_guidance_scale: 3.0
          unconditional_guidance_label:
          - ''
  trainer:
    benchmark: true
    val_check_interval: 5000000
    num_sanity_val_steps: 0
    accumulate_grad_batches: 1